site_name: Mi Documentaci√≥n del Proyecto
nav:
  - Inicio: index.md
  - API: api.md

theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python  # Usa el handler para Python